---
title: "Iterative Solutions for Debye Huckel Equation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Introduction

If the activity coefficients or ionic strength of a solute in solution is known, the other value can be solved for. However, if neither are known, iterative solutions must be employed to determine both the activity coefficients and the ionic strength. 
First, the activity coefficients are assumed to be 1. The ionic strength is then calculated based on these values and the concentration of the solutes in solution. Secondly, the ionic strength and relevant coefficients can be used in the Debye-Huckel equation to solve for the activity coefficients. These coefficients can then be used to repeat Step 1. The cycle is performed until the values obtained from two successive cycles produce similar answers. 
We created a database with the relevant and necessary constants required for determination of ionic strength and the activity coefficients for a variety of species, such as hydrated radius, solubility constants, etc. We also wrote a program to access these constants and utilize them in the equations for ionic strength and Debye-Huckel. We wrote this program in RStudio, utilizing Python blocks. The primary resource utilized for the necessary equations in this project is the eight edition of the "Quantitative Chemical Analysis" textbook by Daniel C. Harris. 

## Solving for Ionic Strength - Brynne Wilson

To use the Debye Huckel equation, the ionic strength ($\mu$) must be known. As such, I used the following equation for ionic strength along with the concentration of the solutes and the charge of the ions (Equation 1). I also worked on writing the code necessary to access the constants and coefficients from the database created by Valerie required in the ionic strength equation (charge and concentration) 

$\mu$= $\frac{1}{2}\sum_{1}^{n} C_{i}Z_{i}$		                                                            	                                (1)  
 

## Solving for Activity Coefficients-Jenna Eubanks-Gray

Using the $\mu$ calculated in the previous section, the hydrated radii from the database, and the charge of the ion in the Debye-Huckel equation shown in Equation (2), the activity coefficient was calculated. 

log($\gamma$)=$\frac{-0.51z^2\sqrt{\alpha}}{1+0.33\alpha\sqrt{\gamma}}$    (2)

The activity coefficient was then used to calculate the ionic strength. Step 1 and Step 2 continue until the answers produced from Step 2 are the same to within 10^(-5) of the last step. I helped design the code to read in the needed values from the database. 

## Creating a Database-Valerie Basurto 

In order to solve for both activity coefficients and for ionic strength, I will create a dictionary that will hold the constants for Ksp, $\mu$, ionic charge, and  $\alpha$, for ions in solution. These constants will be pulled from the dictionary to be used in equations 1 and 2. 

a csv file will be used to import the data into the code. An example of the data is shown bellow. 

Ion    charge   $\alpha$     
H+       +1        900      

```{python}
import math 
#This package was required to execute the math.sqrt function in the while loop below. 
import pandas as pd 
#This package was required to access and pull values from the data frames containing the constants. 
Difference = 1 
#Difference was initially defined as 1 to allow the while loop below to run. 

Table1 = pd.read_csv("ComputingTable1.csv",
                 index_col=0)

ion1 = "Enter first ion here"
ion2 = "Enter second ion here"
concentration = Enterconcentrationhere
compound = "Enter compound here"

print(ion1) 
print(ion2) 
charge1 = Table1["CHARGE"][ion1] 
charge2 = Table1["CHARGE"][ion2] 
alpha1 = Table1["$ALPHA$"][ion1] 
alpha2 = Table1["$ALPHA$"][ion2] 
ksp = Table1["Ksp"][compound] 
activitycoefficient1 = 1
activitycoefficient2 = 1
#The activity coefficients are initially assumed to be 1 because they are unknown. 
activity1 = math.sqrt(ksp/(activitycoefficient1*activitycoefficient2))
activity2 = math.sqrt(ksp/(activitycoefficient1*activitycoefficient2))
mu = 0.5*(concentration*(charge1)**2 + concentration*(charge2)**2)

sqrtmu = math.sqrt(mu) 
activitycoefficienta = 10**(-0.51*(charge1**2)*(sqrtmu))/(1+alpha1*(sqrtmu)/305)
activitycoefficientb = 10**(-0.51*(charge2**2)*(sqrtmu))/(1+alpha2*(sqrtmu)/305)
#The above equations are used to calculate the new activity coefficients from the mu calculated above. 

#The while loop below will continue until the difference, which is defined below, is less than 0.00001. 
while Difference>0.00001:
  #Step 1: Brynne
  activitya = math.sqrt(ksp/(activitycoefficienta*activitycoefficientb))
  activityb = math.sqrt(ksp/(activitycoefficienta*activitycoefficientb))
  muA = 1/2*(activitya*(charge1)**2 + activityb*(charge2)**2)
    
  #Step 2: Jenna   
  #Step 2 and 4 are used to calculate the activity coefficients from the mu found in Step 1 and 3, the charges of the ions, and the hydrated radius. 
  sqrtmuA = math.sqrt(muA)
  activitycoefficientc = 10**(-0.51*(charge1**2)*(sqrtmuA))/(1+alpha1*(sqrtmuA)/305)
  activitycoefficientd = 10**(-0.51*(charge2**2)*(sqrtmuA))/(1+alpha2*(sqrtmuA)/305)
     
  #Step 3: Brynne 
  activityc = math.sqrt(ksp/(activitycoefficientc*activitycoefficientd))
  activityd = math.sqrt(ksp/(activitycoefficientc*activitycoefficientd))
  muB = 1/2*(activityc*(charge1)**2 + activityd*(charge2)**2)
      
  #Step 4: Jenna  
  sqrtmuB = math.sqrt(muB) 
  activitycoefficienta = 10**(-0.51*(charge1**2)*(sqrtmuA))/(1+alpha1*(sqrtmuA)/305)
  activitycoefficientb = 10**(-0.51*(charge2**2)*(sqrtmuA))/(1+alpha2*(sqrtmuA)/305)
      
  Difference = activitycoefficientb - activitycoefficientd   
  #This variable is defined in order to determine when the while loop should end. The while loop will end when the values calculated for the activity coefficients are very close. 
  
print(activitycoefficientc)
print(activitycoefficientd)
```
